Repository theSolution2y/thesolution2y, pull requests merged in 2021-12, with the labels that each got.

#20 favicon has been created
  public/icon/favicon.ico
  resources/views/layout/layout.blade.php
Labels: Ready to Test

#23 Changes have been made
  docs/installation.md
Labels: Ready to Review

#26 image upload in category of backend has been fixed
  app/Http/Controllers/CategoryController.php
  resources/views/backend/category/index.blade.php
Labels: Ready to Test

#25 24 make about us page layout
  public/frontend/about.css
  resources/views/about.blade.php
  routes/web.php
Labels: Ready to Test

#22 make migration for contributors table is done.
  database/migrations/2021_12_22_093419_contributors_table.php
Labels: Ready to Test

#27 admin category update functionality
  app/Http/Controllers/CategoryController.php
  resources/views/backend/category/index.blade.php
  resources/views/backend/category/update.blade.php
Labels: Ready to Test

#29 migrations for contact us has been created
  database/migrations/2021_12_23_135438_create_contact_us_table.php
Labels: Ready to Review

#32 installation guide final changes made
  docs/installation.md
Labels: Ready to Test

#33 update functionality working
  app/Http/Controllers/CategoryController.php
Labels: Ready to Test

#38 Issue has been resolved
  app/Http/Controllers/CategoryController.php
  resources/views/backend/category/index.blade.php
  routes/web.php
Labels: Ready to Test, backend

#34 change file path is done.
  resources/views/contributor.blade.php
  resources/views/dashboard/contributor.blade.php
Labels: Ready to Test

#41 details column has been added in categories page in the admin panel
  resources/views/backend/category/index.blade.php
Labels: Ready to Test, backend, admin

#42 Contributor route function changes are done.
  routes/web.php
Labels: Ready to Test, status:reviewed

#50 Details column has been made in post page
  resources/views/backend/post/index.blade.php
Labels: Ready to Review, backend, admin

#52 admin bg change
  resources/views/backend/dashboard.blade.php
Labels: frontend, admin

#53 new animation for admin dashboard
  resources/views/backend/dashboard.blade.php
Labels: frontend, admin

#58 admin login check done
  app/Http/Controllers/AdminController.php
  resources/views/backend/admincheck.blade.php
  resources/views/backend/category/add.blade.php
  resources/views/backend/category/index.blade.php
  resources/views/backend/category/update.blade.php
  resources/views/backend/dashboard.blade.php
  resources/views/backend/post/add.blade.php
  resources/views/backend/post/index.blade.php
  resources/views/backend/post/update.blade.php
  routes/web.php
Labels: Ready to Review, backend, admin, Point:3
