Repository theSolution2y/thesolution2y, pull requests merged in 2022-02, with the labels that each got.

#137 layout CSS and Home page css slight changes
  public/frontend/home.css
  public/frontend/layout.css
Labels: Ready to Review

#143 user authorisation
  app/Http/Controllers/Auth/ConfirmPasswordController.php
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/Auth/VerificationController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/SigninController.php
  app/Http/Controllers/SignupController.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  resources/js/bootstrap.js
  resources/sass/_variables.scss
  resources/sass/app.scss
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/confirm.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/verify.blade.php
  resources/views/layout/layout.blade.php
  resources/views/layouts/app.blade.php
  resources/views/login.blade.php
  routes/web.php
  webpack.mix.js
Labels: Ready to Test, backend

#140 slight changes in home page and layout
  public/frontend/home.css
  public/frontend/layout.css
  resources/views/layout/layout.blade.php
Labels: Ready to Review

#144 119 change in layout page frontend
  public/frontend/home.css
  public/frontend/layout.css
  public/frontend/layout.js
  resources/views/layout/layout.blade.php
Labels: Ready to Review

#146 html of study page has been completed
  resources/views/study.blade.php
Labels: Ready to Review

#149 html of reading section has been completed
  resources/views/read.blade.php
Labels: Ready to Review

#150 Favicon has started showing
  resources/views/layout/layout.blade.php
Labels: Ready to Review

#151 pdf upload from admin
  app/Http/Controllers/PostController.php
  database/migrations/2021_12_16_095546_create_posts_table.php
  resources/views/backend/post/add.blade.php
Labels: Ready to Review, backend

#152 Social links have been updated
  public/frontend/layout.css
  resources/views/layout/layout.blade.php
Labels: Ready to Review

#153 layout.app remove
  resources/views/auth/register.blade.php
Labels: Ready to Review, backend

#155 Minor changes have been done
  composer.lock
  resources/views/study.blade.php
Labels: Ready to Review

#157 about-us-page
  public/frontend/about.css
  resources/views/about.blade.php
Labels: frontend

#158 Home page css
  public/frontend/layout.css
  resources/views/layout/layout.blade.php
Labels: Ready to Test, status:reviewed

#160 contactus-page-frontend-added
  public/frontend/contact.css
  resources/views/contact.blade.php
Labels: Ready to Review

#161 read and study page functionality has been done
  public/frontend/layout.css
  public/frontend/layout.js
  public/frontend/read.js
  public/frontend/reading.css
  public/frontend/study.css
  public/imgs/1644123471.png
  public/imgs/1644155511.jpg
  public/imgs/1644156480.png
  public/imgs/1644156507.png
  public/imgs/1644156529.png
  public/imgs/1644156559.png
  public/imgs/1644157225.png
  resources/views/read.blade.php
  resources/views/study.blade.php
Labels: Ready to Review

#162 pdf showing in user side
  app/Http/Controllers/ChapterController.php
  app/Http/Controllers/PostController.php
  database/migrations/2021_12_16_095546_create_posts_table.php
  package-lock.json
  package.json
  resources/views/backend/post/add.blade.php
  resources/views/chapter.blade.php
  resources/views/read.blade.php
  routes/web.php
Labels: Ready to Review, frontend, backend, Point:3, Priority: High

#159 Content has been added
  resources/views/about.blade.php
  resources/views/home.blade.php
  resources/views/layout/layout.blade.php
Labels: Ready to Review

#165 About Us minor changes
  resources/views/about.blade.php
Labels: Ready to Review

#168 reading page has been completed
  public/frontend/layout.css
  public/frontend/reading.css
  public/frontend/study.css
  resources/views/chapter.blade.php
  resources/views/contributor.blade.php
  resources/views/course.blade.php
  resources/views/read.blade.php
Labels: Ready to Review

#171 About page modified
  public/contributor_img/aadarsh.jpg
  public/frontend/about.css
  resources/views/about.blade.php
Labels: Ready to Review
