Repository theSolution2y/thesolution2y, pull requests merged in 2022-01, with the labels that each got.

#65 hamburger close on outside click has been done
  public/frontend/layout.js
Labels: Ready to Review

#63 home page and logo animation has been completed
  public/frontend/contact.css
  public/frontend/home.css
  public/frontend/layout.css
  public/imgs/logo.png
  resources/views/home.blade.php
  resources/views/layout/layout.blade.php
Labels: Ready to Review, frontend

#67 contact us li has been done
  resources/views/layout/layout.blade.php
  routes/web.php
Labels: Ready to Review

#68 Merge conflicts has been resolved
  app/Http/Controllers/ContactController.php
  app/Models/Contact.php
  database/migrations/2022_01_02_084748_create_contacts.php
  public/frontend/contact.css
  resources/views/contact.blade.php
  routes/web.php
Labels: Ready to Review, backend, farziwada

#72 8 about us
  public/frontend/about.css
  resources/views/about.blade.php
Labels: Ready to Review

#69 54 contributors form submission functionality.
  app/Http/Controllers/ContributorController.php
  app/Models/Contributor.php
  database/migrations/2021_12_22_093419_create_contributors_table.php
  resources/views/contributor.blade.php
  resources/views/layout/layout.blade.php
  routes/web.php
Labels: Ready to Review

#73 frontend study section
  app/Http/Controllers/StudyController.php
  public/frontend/reading.css
  resources/views/home.blade.php
  resources/views/layout/layout.blade.php
  resources/views/read.blade.php
  resources/views/study.blade.php
  routes/web.php
Labels: Ready to Review, frontend, user

#86 60 removed title tag from layout page
  resources/views/layout/layout.blade.php
Labels: Ready to Review

#90 card flip has been done
  public/frontend/about.css
  resources/views/about.blade.php
Labels: Ready to Review

#91 pdf upload form admin side is done.
  app/Http/Controllers/PostController.php
  database/migrations/2021_12_16_095546_create_posts_table.php
  resources/views/backend/post/index.blade.php
Labels: Ready to Review

#92 user signup and login page is done.
  public/frontend/login.css
  resources/views/layout/layout.blade.php
  resources/views/login.blade.php
  routes/web.php
Labels: Ready to Review

#94 changes are done.
  public/frontend/login.css
  resources/views/layout/layout.blade.php
  resources/views/login.blade.php
  routes/web.php
Labels: Ready to Review

#96 88 theme change
  public/frontend/layout.css
  public/frontend/layout.js
  resources/views/layout/layout.blade.php
Labels: Ready to Test

#95 changes have been made on the contact us page
  app/Models/Contact.php
  database/migrations/2022_01_02_084748_create_contacts.php
  public/frontend/contact.css
  resources/views/contact.blade.php
  routes/web.php
Labels: enhancement, Ready to Test, backend

#97 image animation has been added
  public/frontend/home.css
  public/imgs/logo.png
Labels: Ready to Review

#98 reading section frontend
  app/Http/Controllers/StudyController.php
  public/frontend/reading.css
  resources/views/read.blade.php
  routes/web.php
Labels: Ready to Review

#102 Contributor form submission solved
  app/Http/Controllers/ContributorController.php
  resources/views/contributor.blade.php
Labels: Ready to Review

#107 every page link in nav menu has been completed
  public/frontend/contact.css
  public/frontend/contributor.css
  public/frontend/home.css
  public/frontend/layout.css
  public/frontend/login.css
  resources/views/home.blade.php
  resources/views/layout/layout.blade.php
Labels: Ready to Review

#109 separation of study and read css files
  public/frontend/reading.css
  public/frontend/study.css
  resources/views/study.blade.php
Labels: Ready to Review

#111 delete button is now working in category section
  routes/web.php
Labels: Ready to Review

#114 layout has been checked succesfully
  public/frontend/home.css
  public/frontend/layout.css
  resources/views/layout/layout.blade.php
Labels: Ready to Test

#115 contactus page has been checked
  public/frontend/contact.css
  resources/views/contact.blade.php
Labels: Ready to Review

#117 changes has been done in contributors page
  public/frontend/contributor.css
  resources/views/contributor.blade.php
Labels: Ready to Review

#126 layout html fixed
  resources/views/layout/layout.blade.php
Labels: Ready to Test, status:reviewed

#130 login page html modified
  resources/views/login.blade.php
Labels: Ready to Review

#128 119-changed-homepage-design-css
  public/frontend/home.css
  public/frontend/layout.css
  public/imgs/background.png
  resources/views/home.blade.php
  resources/views/layout/layout.blade.php
Labels: Ready to Review

#131 input password
  resources/views/contact.blade.php
  resources/views/login.blade.php
Labels: Ready to Review
